/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Canonical reference frame for any spacetime event across the emperor's portfolio. WGS84 geodetic position + UTC timestamp. Adopted by the Mathematician in Session 3; ruled binding in Session 4.
 */
export interface WorldCoordinateEvent {
  /**
   * Semver. Major bump on breaking change; minor on additive; patch on cosmetic.
   */
  schema_version: string;
  event_type:
    | "satellite_position"
    | "ground_observation"
    | "hardware_capture"
    | "plant_status_change"
    | "ground_station"
    | "user_defined";
  position: {
    /**
     * Geodetic latitude in degrees (WGS84 by default). Positive north.
     */
    lat_deg: number;
    /**
     * Longitude in degrees. Positive east.
     */
    lon_deg: number;
    /**
     * Altitude in meters. Reference frame named by 'frame' below.
     */
    alt_m: number;
    /**
     * Reference frame for the altitude value. WGS84_ellipsoid is the default and preferred frame.
     */
    frame: "WGS84_ellipsoid" | "WGS84_MSL" | "ECEF_meters";
    /**
     * 1-sigma spherical position uncertainty in meters. Required for measured positions; omit for user-defined.
     */
    uncertainty_m?: number;
    [k: string]: unknown;
  };
  /**
   * ISO-8601 UTC. Must include the 'Z' suffix or explicit +00:00 offset. Local times are rejected.
   */
  timestamp_utc: string;
  /**
   * 1-sigma timing uncertainty in seconds. TLE-derived positions should carry the epoch age here in seconds.
   */
  timestamp_uncertainty_s?: number;
  /**
   * Provenance chain. Required when the event was ingested from an external source.
   */
  source?: {
    /**
     * The authoritative record. e.g. 'USSPACECOM catalog', 'GOGPT Jan 2026 release'.
     */
    primary?: string;
    /**
     * Any intermediary. e.g. 'n2yo.com', 'CelesTrak'. Must be named when the primary was not fetched directly.
     */
    aggregator?: string;
    fetched_at_utc?: string;
    license?: "CC-BY-4.0" | "GPL-family" | "proprietary-with-ToS" | "public-domain" | "unknown";
    [k: string]: unknown;
  };
  /**
   * Event-type-specific payload. Structure not enforced by this schema.
   */
  metadata?: {
    [k: string]: unknown;
  };
}
