/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A time-series metric of a country's energy/emissions profile in a given year, sourced from OWID (Our World in Data) or IRENA. Adopted in Session 5 (Wave 2 ingest) to carry mixed-license OWID Ember+EI rows and pinned IRENA statistics without losing per-row provenance.
 */
export interface EnergySupplySeries {
  /**
   * Semver. Major bump on breaking change; minor on additive; patch on cosmetic.
   */
  schema_version: string;
  /**
   * The metric this record reports. *_by_technology metrics require the technology field.
   */
  metric:
    | "co2_per_capita_t"
    | "co2_per_gdp_kg_per_intl_dollar"
    | "electricity_share_pct_by_source"
    | "electricity_share_renewables_pct"
    | "renewable_capacity_mw_by_technology"
    | "renewable_generation_gwh_by_technology"
    | "renewable_capacity_additions_mw"
    | "lcoe_usd_per_mwh_by_technology";
  /**
   * ISO 3166-1 alpha-3 country code, or an OWID World-Bank-style aggregate code (e.g. 'OWID_WRL' for World, 'OWID_EU27' for the EU-27 grouping). Not a strict ISO code for aggregates — see known_failure_modes.
   */
  country_iso3: string;
  /**
   * Calendar year the value applies to. Global Carbon Budget's per-capita CO2 series extends back to the 1700s for some countries.
   */
  year: number;
  /**
   * The metric value, in the unit named by 'unit'.
   */
  value: number;
  /**
   * Unit of the value, e.g. 't', 'kg_per_intl_dollar', 'pct', 'MW', 'GWh', 'USD_per_MWh'.
   */
  unit: string;
  /**
   * Required (in practice) for *_by_technology metrics. e.g. 'solar_pv', 'onshore_wind', 'offshore_wind', 'hydropower', 'bioenergy', 'geothermal', 'coal', 'gas', 'oil', 'nuclear', 'other_renewables'.
   */
  technology?:
    | "solar_pv"
    | "onshore_wind"
    | "offshore_wind"
    | "hydropower"
    | "bioenergy"
    | "geothermal"
    | "marine"
    | "coal"
    | "gas"
    | "oil"
    | "nuclear"
    | "other_renewables"
    | "renewables_total";
  /**
   * Critical for the OWID mixed-license datasets. e.g. 'Ember' vs 'Energy Institute'. MUST be preserved per-row; never compacted away.
   */
  sub_source?: "Ember" | "Energy Institute" | "Global Carbon Budget" | "Maddison Project 2023" | "IRENA" | "OWID";
  /**
   * Provenance chain. Required on every record.
   */
  source: {
    /**
     * The upstream organization that produced the underlying figure. e.g. 'Ember', 'Energy Institute', 'Global Carbon Project', 'Maddison Project', 'IRENA'.
     */
    primary: string;
    /**
     * The aggregator that republished the primary data. 'OWID' or 'IRENA' — nullable if fetched directly from the primary.
     */
    aggregator: string | null;
    /**
     * ISO-8601 UTC timestamp of the fetch that produced this record.
     */
    fetched_at_utc: string;
    /**
     * Upstream license identifier for this specific row, e.g. 'CC BY 4.0', '© Energy Institute 2025', '© IRENA 2025'.
     */
    license: string;
    /**
     * Verbatim required attribution string for this row. Must travel with the value, not just the file header.
     */
    citation: string;
    /**
     * OWID grapher slug this record was fetched from, e.g. 'co-emissions-per-capita'. Null if not an OWID-sourced record.
     */
    owid_slug: string | null;
    /**
     * IRENA publication citation this record was pinned from, e.g. 'IRENA (2025), Renewable capacity statistics 2025, International Renewable Energy Agency, Abu Dhabi.'. Null if not an IRENA-sourced record.
     */
    irena_publication: string | null;
    [k: string]: unknown;
  };
}
