/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An instantaneous or short-interval measurement from a geophysical monitoring source — NOAA SWPC space weather, USGS earthquakes, or JPL HORIZONS ephemerides. Adopted in Session 5 (Wave 2 ingest).
 */
export interface GeophysicalEvent {
  /**
   * Semver. Major bump on breaking change; minor on additive; patch on cosmetic.
   */
  schema_version: string;
  /**
   * The kind of geophysical measurement this record reports. kp_index_3h and kp_index_1m are separate NOAA products and must never be compared directly.
   */
  event_kind:
    | "kp_index_3h"
    | "kp_index_1m"
    | "solar_wind_speed_km_s"
    | "solar_wind_density_p_cc"
    | "earthquake_magnitude"
    | "earthquake_depth_km"
    | "planet_position_au";
  /**
   * ISO-8601 UTC. Must include the 'Z' suffix or explicit +00:00 offset. Local times are rejected.
   */
  timestamp_utc: string;
  /**
   * The measurement value, in the unit named by 'unit'.
   */
  value: number;
  /**
   * Unit of the value, e.g. 'kp_unitless', 'km_s', 'p_cc', 'mww', 'ml', 'md', 'km', 'au'.
   */
  unit: string;
  /**
   * Required in practice for earthquake_magnitude records. USGS magnitude scale used, e.g. 'mww', 'ml', 'md', 'mb'. Magnitudes on different scales are not directly comparable.
   */
  magnitude_type?: "mww" | "mwc" | "mwb" | "mwr" | "ml" | "md" | "mb" | "ms";
  /**
   * For HORIZONS: the body whose position/state is reported, e.g. 'Sun', 'Moon', 'Mars'.
   */
  target_body?: string;
  /**
   * For HORIZONS: the observer/center and frame convention used, e.g. '@sun', '500@399', '500@10'. Required to interpret target_body positions correctly.
   */
  reference_frame?: string;
  /**
   * Optional WorldCoordinateEvent-style position object, inlined here to avoid a cross-schema $ref. For solar-wind measurements, refers to the spacecraft location; for earthquakes, the hypocenter; for planet positions, geocentric or heliocentric coordinates.
   */
  position?: {
    /**
     * Latitude in degrees. Positive north. For heliocentric/geocentric planet positions, may represent ecliptic latitude.
     */
    lat_deg: number;
    /**
     * Longitude in degrees. Positive east. For heliocentric/geocentric planet positions, may represent ecliptic longitude.
     */
    lon_deg: number;
    /**
     * Altitude/depth in meters where applicable (e.g. earthquake hypocenter depth converted to meters).
     */
    alt_m?: number;
    /**
     * Reference frame for the position. Earthquake hypocenters use WGS84_ellipsoid; HORIZONS vectors use heliocentric_ecliptic or geocentric_equatorial; solar-wind spacecraft use spacecraft_ephemeris.
     */
    frame:
      | "WGS84_ellipsoid"
      | "WGS84_MSL"
      | "ECEF_meters"
      | "heliocentric_ecliptic"
      | "geocentric_equatorial"
      | "spacecraft_ephemeris";
    /**
     * 1-sigma position uncertainty in meters, when known (e.g. USGS horizontal error).
     */
    uncertainty_m?: number;
    [k: string]: unknown;
  };
  /**
   * Provenance chain. Required on every record.
   */
  source: {
    /**
     * The authoritative record, e.g. 'NOAA Space Weather Prediction Center', 'USGS Earthquake Hazards Program', 'JPL Horizons System'.
     */
    primary: string;
    /**
     * Any intermediary. Nullable — these three sources are fetched directly, so this is typically null.
     */
    aggregator: string | null;
    /**
     * ISO-8601 UTC timestamp of the fetch that produced this record.
     */
    fetched_at_utc: string;
    /**
     * 'public-domain-USG' for NOAA/USGS (17 U.S.C. § 105), 'public-domain-NASA' for JPL HORIZONS.
     */
    license: "public-domain-USG" | "public-domain-NASA";
    /**
     * Verbatim courtesy citation string for this record's source, per UPSTREAM_TERMS.md.
     */
    citation: string;
    [k: string]: unknown;
  };
}
