/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Hand-maintained SDR hardware compatibility matrix for SatDump. This is our original commentary, not SatDump's file. Ruled binding in Session 4 (no SatDump source, binary, or config file enters this tree).
 */
export interface HardwareCompatMatrix {
  schema_version: string;
  /**
   * When this matrix was last compiled by the maintainer.
   */
  compiled_at_utc: string;
  /**
   * Range of SatDump versions this matrix targets (e.g. '>=1.2.0 <2.0').
   */
  satdump_version_range?: string;
  devices: {
    /**
     * Stable id (e.g. 'rtl-sdr-v3', 'airspy-mini', 'hackrf-one').
     */
    device_id: string;
    display_name: string;
    platform_support: {
      desktop: boolean;
      android: boolean;
      notes?: string;
      [k: string]: unknown;
    };
    frequency_range_hz: {
      min: number;
      max: number;
      [k: string]: unknown;
    };
    /**
     * Maximum continuous sample rate without USB drops on typical hardware.
     */
    max_sample_rate_hz: number;
    /**
     * Effective ADC bit depth. Physicist warned: this drives quantization noise floor.
     */
    adc_bits?: number;
    typical_use_cases?: (
      | "noaa_apt_137MHz"
      | "meteor_lrpt_137MHz"
      | "goes_hrit_1.7GHz"
      | "iridium_1.6GHz"
      | "airband_118MHz"
      | "amateur_vhf_uhf"
      | "hf_wideband"
      | "general_purpose"
    )[];
    /**
     * Approximate street price at time of matrix compile. Not a quote.
     */
    price_usd_approx?: number;
    notes?: string;
  }[];
}
