/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A single Two-Line Element set cached locally, with epoch age discipline enforced. Ruled binding in Session 3 (aggregator-vs-source) and Session 4 (rate-of-change gate).
 */
export interface TLECacheEntry {
  schema_version: string;
  /**
   * The NORAD catalog ID. This is canonical, not the aggregator's 57-category taxonomy.
   */
  norad_cat_id: number;
  /**
   * Human-readable object name (e.g. 'ISS (ZARYA)').
   */
  object_name: string;
  /**
   * COSPAR designator, e.g. '1998-067A'.
   */
  international_designator?: string;
  /**
   * Line 1 of the TLE, exactly 69 characters per NORAD spec.
   */
  tle_line1: string;
  /**
   * Line 2 of the TLE, exactly 69 characters per NORAD spec.
   */
  tle_line2: string;
  /**
   * ISO-8601 UTC of the TLE's own epoch (parsed from line 1).
   */
  epoch_utc: string;
  /**
   * Age of the TLE at fetch time, in days. Consumers MUST degrade confidence past 3.0.
   */
  epoch_age_days_at_fetch?: number;
  fetched_at_utc: string;
  source: {
    /**
     * The authoritative record. USSPACECOM/Space-Track is the state catalog.
     */
    primary: "USSPACECOM/Space-Track" | "CelesTrak" | "user_upload";
    /**
     * Named separately from primary. When null, primary was fetched directly.
     */
    aggregator?: "n2yo.com" | "CelesTrak" | "Heavens-Above" | null;
    url_fetched?: string;
    /**
     * The most restrictive binding in the provenance chain sets the ceiling.
     */
    license_binding?: "public-domain" | "space-track-ToS" | "aggregator-ToS";
    [k: string]: unknown;
  };
  /**
   * True if the TLE was validated for SGP4 propagation locally (checksums verified, ranges sane).
   */
  sgp4_ready?: boolean;
}
